### ISSUE TITLE
JDBC Jars Corrupted.  

### ISSUE THREAD

**Issue by Syed-SnapLogic** [awsdocs/amazon-athena-user-guide#80]
The jdbc jars for athena listed in this page https://docs.aws.amazon.com/athena/latest/ug/connect-with-jdbc.html are corrupted.
    - https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC-2.0.29.1000/AthenaJDBC41.jar
    - https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC-2.0.29.1000/AthenaJDBC42.jar

Both the above JARs are missing the driver class com.simba.athena.jdbc.Driver.

**Comment by taammann** [comment]
Hi Syed,
Thanks for bringing this issue to our attention. The Athena team is investigating and will get it corrected as soon as possible.

**Comment by Syed-SnapLogic** [comment]
How and when do we know its corrected?

**Comment by taammann** [comment]
The downloads have been corrected. Thanks for letting us know.

**Comment by Syed-SnapLogic** [comment]
@taammann , JDBC42.jar is fine.  But the Driver is still missing in the JDBC41.jar (FYI).

![image](https://user-images.githubusercontent.com/5888194/168824889-957b8739-04b6-4f94-a254-a593469a1d8b.png)

**Comment by taammann** [comment]
Thanks. I've alerted the Athena team and they are investigating.

**Comment by Syed-SnapLogic** [comment]
@taammann , I am having some trouble with Athena JDBC Driver.  Unable to fetch the list of tables.  I am not able to find the source code online.
Can you help me locate the source code?  Or is there any support portal where I can directly ask questions to JDBC developers?  thanks.

**Comment by taammann** [comment]
Syed,
For help on your specific issue, contact AWS Support (in the AWS console, choose **Support**, **Support Center**) or ask a question on [AWS re:Post](https://repost.aws/tags/TA78iVOM7gR62_QqDe2-CmiA/amazon-athena) using the **Amazon Athena** tag.

**Comment by Syed-SnapLogic** [comment]
Thanks @taammann . Let me know once the 41 jar is corrected.
